import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { headers } from "next/headers";
import { ClientFunction } from "./ClientFunction";
import { GoogleTagMgr } from "@/components/GoogleTagMgr";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const nonce = headers().get("x-nonce");

  return (
    <html lang="en">
      <body className={inter.className}>
        <>
          <GoogleTagMgr nonce={nonce} />
          <ClientFunction nonce={nonce}>{children}</ClientFunction>
        </>
      </body>
    </html>
  );
}
